import type { Venue } from "@/lib/types";

export const sampleVenues: Venue[] = [
  {
    id: "sample-1",
    name: "札幌コンベンションホール",
    address: "北海道札幌市白石区東札幌6条1丁目",
    event_date: "2026-04-15",
    fee: 180000,
    status: "booked",
    lat: 43.0618,
    lng: 141.3545,
    contact_tel: "",
    contact_fax: "",
    contact_email: "",
    permit_file_path: null,
    permit_file_name: null,
    conversation_notes: [],
    editor_email: "system@example.local",
  },
  {
    id: "sample-2",
    name: "仙台イベントプラザ",
    address: "宮城県仙台市青葉区本町2丁目",
    event_date: "2026-04-22",
    fee: 125000,
    status: "candidate",
    lat: 38.2682,
    lng: 140.8694,
    contact_tel: "",
    contact_fax: "",
    contact_email: "",
    permit_file_path: null,
    permit_file_name: null,
    conversation_notes: [],
    editor_email: "system@example.local",
  },
  {
    id: "sample-3",
    name: "東京ベイカンファレンス",
    address: "東京都江東区有明3丁目",
    event_date: "2026-05-08",
    fee: 260000,
    status: "booked",
    lat: 35.6329,
    lng: 139.7947,
    contact_tel: "",
    contact_fax: "",
    contact_email: "",
    permit_file_path: null,
    permit_file_name: null,
    conversation_notes: [],
    editor_email: "system@example.local",
  },
  {
    id: "sample-4",
    name: "名古屋アーバンホール",
    address: "愛知県名古屋市中村区名駅4丁目",
    event_date: "2026-05-14",
    fee: 148000,
    status: "candidate",
    lat: 35.1709,
    lng: 136.8815,
    contact_tel: "",
    contact_fax: "",
    contact_email: "",
    permit_file_path: null,
    permit_file_name: null,
    conversation_notes: [],
    editor_email: "system@example.local",
  },
  {
    id: "sample-5",
    name: "大阪クリエイティブセンター",
    address: "大阪府大阪市北区大深町3丁目",
    event_date: "2026-05-23",
    fee: 215000,
    status: "booked",
    lat: 34.7025,
    lng: 135.4959,
    contact_tel: "",
    contact_fax: "",
    contact_email: "",
    permit_file_path: null,
    permit_file_name: null,
    conversation_notes: [],
    editor_email: "system@example.local",
  },
  {
    id: "sample-6",
    name: "福岡ハーバー会議室",
    address: "福岡県福岡市博多区沖浜町7丁目",
    event_date: "2026-06-04",
    fee: 132000,
    status: "candidate",
    lat: 33.593,
    lng: 130.4147,
    contact_tel: "",
    contact_fax: "",
    contact_email: "",
    permit_file_path: null,
    permit_file_name: null,
    conversation_notes: [],
    editor_email: "system@example.local",
  },
];
